trigger:
  branches:
    include:
    - SPRINT

  paths:
    include:
    - futurenhs.app/*

jobs:
- job: CheckChangesInPaths
  displayName: 'Check commit contains changes for FutureNHS App'
  pool:
    vmImage: 'windows-latest'
  steps: 
  - powershell: |
     $buildsUrl = "$(System.CollectionUri)/$(System.TeamProject)/_apis/build/builds?definitions=$(System.DefinitionId)&resultFilter=succeeded&queryOrder=descending&api-version=6.0-preview"
     $buildsresult = Invoke-RestMethod -Uri $buildsUrl -Headers @{Authorization = "Bearer $(System.AccessToken)"} -Method GET
     
     $buildId = $buildsresult.value[0].id
     if($buildId -eq $null)
     {
          $matchFound=$true
          echo "##vso[task.setvariable variable=futurenhs.app;isOutput=true]$True"
     }
     else
     {
      echo "Build to check from: $buildId to: $(Build.BuildId)"
      $commitsUrl = "$(System.CollectionUri)/$(System.TeamProject)/_apis/build/changes?fromBuildId=$buildId&toBuildId=$(Build.BuildId)&api-version=6.0-preview.2"
      $commitsresult = Invoke-RestMethod -Uri $commitsUrl -Headers @{Authorization = "Bearer $(System.AccessToken)"} -Method GET
     
      foreach($commit in $commitsresult.value)
      {
       $commitId = $commit.id
       echo "Checking commit for changes: $commitId"
       $url="$(System.CollectionUri)/$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.ID)/commits/$commitId/changes?api-version=5.1"
       $result = Invoke-RestMethod -Uri $url -Headers @{Authorization = "Bearer $(System.AccessToken)"} -Method GET
     
       $changesFolder  = $result.changes | Where-Object{$_.item.gitObjectType -match "tree"} | Select-Object -Property {$_.item.path}
       $matchFound=$False
       foreach($path in $changesFolder ){
        if($path -match '/FutureNHS.Data'){
          $matchFound=$true
          echo "##vso[task.setvariable variable=futurenhs.app;isOutput=true]$True"      
          break
         }       
        }
        if($matchFound)
        {
          echo "Changed detected in FutureNHS.App in commit: $commitId - Stopping..."
          break
        }
      }
     }
    name: ChangesInPaths

- job: BuildNextApp
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.17.4'
    
  - task: Npm@1
    displayName: 'Npm install'
    inputs:
      command: 'install'
      workingDir: '$(Build.SourcesDirectory)/futurenhs.app'
    
  - task: gulp@0
    displayName: 'Build front end assets'
    inputs:
      gulpFile: '$(Build.SourcesDirectory)/futurenhs.app/gulpfile.js'
      targets: 'build'
      gulpjs: '$(Build.SourcesDirectory)/futurenhs.app/node_modules/gulp/bin/gulp.js'

  - task: Npm@1
    displayName: 'Build Next.js assets'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)/futurenhs.app'
      customCommand: 'run build'

  - task: Npm@1
    displayName: 'Unit tests'
    inputs:
      command: 'custom'
      workingDir: '$(Build.SourcesDirectory)/futurenhs.app'
      customCommand: 'run test-js'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/futurenhs.app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/FNHSvNextApp.zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'FNHSvNextApp'
      publishLocation: 'pipeline'

  - task: PublishTestResults@2
    displayName: 'Publish Unit Test Results'
    inputs:
      testResultsFiles: 'jest-junit.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/futurenhs.app/test-reports/unit'
      testRunTitle: 'Unit Test Run'
    continueOnError: true

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage from Unit Tests'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/futurenhs.app/test-reports/unit/cobertura-coverage.xml'
      failIfCoverageEmpty: true

  - task: PowerShell@2
    displayName: 'Add RUN Tag to trigger Release'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      targetType: 'inline'
      script: |
        $user = ""
        $token = $env:SYSTEM_ACCESSTOKEN

        $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(("{0}:{1}" -f $user,$token)))

        $org = "$(System.CollectionUri)"
        $teamProject = "$(System.TeamProject)"
        $buildId = "$(Build.BuildId)"
        $tagName = "RUN"

        $restApiUpdateBuild = "$org/$teamProject/_apis/build/builds/$buildId/tags/$tagName`?api-version=6.0"

        function InvokePutReques ($PutUrl)
        {   
            return Invoke-RestMethod -Uri $PutUrl -Method Put -ContentType "application/json" -Headers @{Authorization=("Basic {0}" -f $base64AuthInfo)}
        }

        $result = InvokePutReques $restApiUpdateBuild
      pwsh: true
