// <auto-generated />
namespace MvcForum.Core.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixMigrationsBlank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixMigrationsBlank));
        
        string IMigrationMetadata.Id
        {
            get { return "202109071320535_FixMigrationsBlank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
