// <auto-generated />
namespace MvcForum.Core.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rowversion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rowversion));
        
        string IMigrationMetadata.Id
        {
            get { return "202105190921331_rowversion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
