export const enum services {
    GET_GROUPS = 'getGroups',
    GET_GROUP = 'getGroup',
    GET_GROUP_ACTIONS = 'getGroupActions',
    GET_GROUP_DISCUSSIONS = 'getGroupDiscussions',
    GET_GROUP_DISCUSSION = 'getGroupDiscussion',
    GET_GROUP_DISCUSSION_COMMENTS = 'getGroupDiscussionComments',
    GET_GROUP_DISCUSSION_REPLIES = 'getGroupDiscussionReplies',
    GET_GROUP_DISCUSSION_COMMENTS_WITH_REPLIES = 'getGroupDiscussionCommentsWithReplies',
    GET_GROUP_FOLDER_CONTENTS = 'getGroupFolderContents',
    GET_GROUP_FOLDER = 'getGroupFolder',
    GET_GROUP_FILE = 'getGroupFile',
    GET_GROUP_MEMBERS = 'getGroupMembers',
    GET_PENDING_GROUP_MEMBERS = 'getGroupPendingMembers',
    GET_GROUP_MEMBER = 'getGroupMember',
    GET_PAGE_TEXT_CONTENT = 'getPageTextContent',
    GET_SEARCH_RESULTS = 'getSearchResults',
    GET_SITE_ACTIONS = 'getSiteActions',
    GET_USER = 'getUser',
    POST_GROUP_DISCUSSION = 'postGroupDiscussion',
    POST_GROUP_DISCUSSION_COMMENT = 'postGroupDiscussionComment',
    POST_GROUP_DISCUSSION_COMMENT_REPLY = 'postGroupDiscussionCommentReply',
    POST_GROUP_FOLDER = 'postGroupFolder',
    POST_GROUP_FILE = 'postGroupFile',
    PUT_GROUP_DETAILS = 'putGroupDetails',
    DELETE_GROUP_MEMBERSHIP = 'deleteGroupMembership',
};