trigger:
 branches:
    include:
    - main
 paths:
    include:
    - MVCForum/*

jobs:

- job: BuildMVCForum
  displayName: 'Build and deploy artifact'
  pool :
    vmImage: 'windows-latest'

  steps:
  - task: NuGetToolInstaller@1
    inputs:
     versionSpec:

  - task: NuGetCommand@2
    displayName: 'Nuget restore'
    inputs:
     command: 'restore'
     restoreSolution: 'MVCForum/MVCForum.sln'
     feedsToUse: 'select'

  - task: NodeTool@0
    displayName: 'Install node'
    inputs:
     versionSpec: '12.22.1'
    
  - task: Cache@2
    displayName: npm Cache
    inputs:
     key: 'npmcache | "$(Agent.OS)" | $(Build.SourcesDirectory)/MVCForum/package.json'
     path: '$(Build.SourcesDirectory)/MVCForum/node_modules'
     cacheHitVar: 'npm_cache_hit'

  - task: Npm@1
    displayName: 'npm install'
    condition: ne(variables.npm_cache_hit, 'true')
    inputs:
     command: 'install'
     workingDir: '$(Build.SourcesDirectory)/MVCForum'
    
  - task: gulp@0
    displayName: 'Build front end'
    inputs:
     workingDirectory: '$(Build.SourcesDirectory)/MVCForum'
     gulpFile: '$(Build.SourcesDirectory)/MVCForum/gulpfilepipeline.js'
     targets: 'buildWeb'
     gulpjs: '$(Build.SourcesDirectory)/MVCForum/node_modules/gulp/bin/gulp.js'
     enableCodeCoverage: false

  - task: MSBuild@1
    displayName: 'Build MVCForum'
    inputs:
     solution: '$(Build.SourcesDirectory)/MVCForum/MVCForum.sln'
     msbuildArchitecture: 'x64'
     configuration: 'Release'
     createLogFile: true
     logFileVerbosity: 'diagnostic'

  - task: CopyFiles@2
    displayName: 'Copy files for artifact'
    inputs:
     SourceFolder: '$(Build.SourcesDirectory)/MVCForum/MVCForum.Website'
     Contents: '**'
     TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact'
    inputs:
     targetPath: '$(Build.ArtifactStagingDirectory)'
     artifact: 'FNHS'
     publishLocation: 'pipeline'

  - task: PublishTestResults@2
    displayName: 'Publish Front End Unit Test Results'
    inputs:
     testResultsFiles: 'jest-junit.xml'
     searchFolder: '$(System.DefaultWorkingDirectory)/js-report'
     testRunTitle: 'Front End Test Run'
    continueOnError: true

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage from Front End Unit Tests'
    inputs:
     codeCoverageTool: Cobertura
     summaryFileLocation: '$(System.DefaultWorkingDirectory)/MVCForum/js-report/cobertura-coverage.xml'
     pathToSources: '$(System.DefaultWorkingDirectory)/MVCForum'
     reportDirectory: '$(System.DefaultWorkingDirectory)/MVCForum/js-report/*.htm'
     failIfCoverageEmpty: true
    continueOnError: true
