DECLARE @autoAdmin AS uniqueidentifier;
SELECT @autoAdmin = id FROM [dbo].[MembershipUser] WHERE Email = 'autoAdmin@test.co.uk'
DECLARE @autoUser AS uniqueidentifier;
SELECT @autoUser = id FROM [dbo].[MembershipUser] WHERE Email = 'autoUser@test.co.uk'
DECLARE @autoUser2 AS uniqueidentifier;
SELECT @autoUser2 = id FROM [dbo].[MembershipUser] WHERE Email = 'autoUser2@test.co.uk'
DECLARE @autoUser3 AS uniqueidentifier;
SELECT @autoUser3 = id FROM [dbo].[MembershipUser] WHERE Email = 'autoUser3@test.co.uk'

-- Delete posts made as part of forumSubmission.feature
DECLARE @forumSubmissionDiscussion AS uniqueidentifier;
SELECT @forumSubmissionDiscussion = id FROM [dbo].[Discussion] WHERE Title = 'forumSubmission Discussion';
DELETE [dbo].[Comment] WHERE [dbo].[Comment].Content LIKE '%Comment posted by the automation%' AND Discussion_Id = @forumSubmissionDiscussion;
DELETE [dbo].[Comment] WHERE [dbo].[Comment].Content LIKE '%This is a reply%' AND Discussion_Id = @forumSubmissionDiscussion;
DELETE [dbo].[Comment] WHERE [dbo].[Comment].Content LIKE '%This is another reply%' AND Discussion_Id = @forumSubmissionDiscussion;

-- Delete discussions generated as part of forumAdmin.feature
	 -- Create a new discussion 
DECLARE @testDiscussion AS uniqueidentifier;
SELECT @testDiscussion = id FROM [dbo].[Discussion] WHERE Title = 'autoTestDiscussion';
DELETE [dbo].[Comment] WHERE Discussion_Id = @testDiscussion;
DELETE [dbo].[Discussion] WHERE Id = @testDiscussion AND CreatedBy = @autoAdmin

-- Delete Folder generated as part of filesManagement.feature
DECLARE @adminGroup AS uniqueidentifier;
SELECT @adminGroup = Id FROM [dbo].[Group] WHERE Name = 'Automation Admin Group'
DELETE FROM [dbo].[Folder] WHERE Group_Id = @adminGroup AND Title != 'Empty Folder' AND Title != 'Automation Test Folder' AND Title != 'Folder 1' AND Title != 'Folder 2' AND Title != 'Folder 3'
DELETE FROM [dbo].[Folder] WHERE Group_Id = @adminGroup AND IsDeleted = 1

-- Delete files uploaded as part of filesNavigation.feature
DECLARE @rootFolder AS uniqueidentifier;
SELECT @rootFolder = Id FROM [dbo].[Folder] WHERE title = 'Empty Folder' AND IsDeleted = 0

DELETE [dbo].[File] WHERE [ParentFolder] = @rootFolder

-- Reset Users to Pending Group Access groupAdmin.feature
	-- Approve group member request
	-- Reject group member request
UPDATE [dbo].[GroupUser] SET Approved = 0, ApprovedToJoinDateUTC = NULL, ApprovingMembershipUser_Id = NULL WHERE MembershipUser_Id = @autoUser2 AND Group_Id = @adminGroup;
UPDATE [dbo].[GroupUser] SET Rejected = 0, ApprovedToJoinDateUTC = NULL, ApprovingMembershipUser_Id = NULL WHERE MembershipUser_Id = @autoUser3 AND Group_Id = @adminGroup;

-- Remove users from groups added as part of automation
	-- Add registered user
DECLARE @publicGroup AS uniqueidentifier;
SELECT @publicGroup = Id FROM [dbo].[Group] WHERE Name = 'Automation Public Group'
DELETE FROM [dbo].[GroupUser] WHERE MembershipUser_Id = @autoUser2 AND Group_Id = @publicGroup

	-- Join a private group
DECLARE @privateGroup AS uniqueidentifier;
SELECT @privateGroup = Id FROM [dbo].[Group] WHERE Name = 'Automation Private Group'
DELETE FROM [dbo].[GroupUser] WHERE MembershipUser_Id = @autoUser AND Group_Id = @privateGroup

-- Remove deleted System Page from database generated by siteAdmin.feature
DELETE [dbo].[SystemPage] WHERE Slug = 'automation-content-page'
DELETE [dbo].[SystemPage] WHERE Slug = 'editable-system-page'
DELETE [dbo].[SystemPage] WHERE Slug = 'deletable-system-page'

--Delete new user details generated
	-- Invite User Form
DELETE [dbo].[GroupInvite] WHERE EmailAddress = 'autoTest@email.com'
	-- New user registration
DELETE [dbo].[MembershipUser] WHERE UserName = 'autoTest@email.com'

--Delete new group generated
	-- Group creation new fields	
DECLARE @groupid AS uniqueidentifier;
SELECT @groupid = id FROM [dbo].[Group] WHERE [Name] = 'alphaGroupTest';

DELETE [dbo].[GroupUser] WHERE Group_Id = @groupid
DELETE [dbo].[Group] WHERE Id = @groupid

-- Reset changes made to Automation Editable Group information
DECLARE @editgroup AS uniqueidentifier;
SELECT @editgroup = id FROM [dbo].[Group] WHERE [Name] = 'Automation Edited Group';
UPDATE [dbo].[Group] SET Name = 'Automation Editable Group',
						 Description = 'DO NOT USE - This group is reserved solely for use by our automated test scripts', 
		 				 PublicGroup = 0, 
		 				 Introduction = 'Introduction ',
						 Image = NULL,
		 				 AboutUs = NULL
					WHERE Id = @editgroup

-- Reset changes made to autoEditUser in edit profile tests
DECLARE @editUser AS uniqueidentifier;
SELECT @editUser = id FROM [dbo].[MembershipUser] WHERE Email = 'autoEditUser@test.co.uk'
UPDATE [dbo].[MembershipUser] SET FirstName = 'autoEdit', 
								  Surname = 'User',
								  Initials = 'AU',
								  Avatar = NULL,
								  Pronouns = ''
							  WHERE Id = @editUser

-- Reset changes made to docTest file in Automation Test Folder
DECLARE @docTest AS uniqueidentifier
SELECT @docTest = id FROM [dbo].[File] WHERE Title = 'Doc Test'
UPDATE [dbo].[File] SET Title = 'docTest', Description = 'test doc' WHERE Id = @docTest