DECLARE @autoAdmin AS uniqueidentifier;
SELECT @autoAdmin = id FROM [dbo].[MembershipUser] WHERE Email = 'autoAdmin@test.co.uk'
DECLARE @autoUser AS uniqueidentifier;
SELECT @autoUser = id FROM [dbo].[MembershipUser] WHERE Email = 'autoUser@test.co.uk'
DECLARE @autoUser2 AS uniqueidentifier;
SELECT @autoUser2 = id FROM [dbo].[MembershipUser] WHERE Email = 'autoUser2@test.co.uk'
DECLARE @autoUser3 AS uniqueidentifier;
SELECT @autoUser3 = id FROM [dbo].[MembershipUser] WHERE Email = 'autoUser3@test.co.uk'

-- Delete posts made as part of forumSubmission.feature
DECLARE @forumSubmissionDiscussion AS uniqueidentifier;
SELECT @forumSubmissionDiscussion = id FROM [dbo].[Discussion] WHERE Title = 'forumSubmission Discussion';
DELETE [dbo].[Comment] WHERE [dbo].[Comment].Content LIKE '%Comment posted by the automation%' AND Discussion_Id = @forumSubmissionDiscussion;
DELETE [dbo].[Comment] WHERE [dbo].[Comment].Content LIKE '%This is a reply%' AND Discussion_Id = @forumSubmissionDiscussion;
DELETE [dbo].[Comment] WHERE [dbo].[Comment].Content LIKE '%This is another reply%' AND Discussion_Id = @forumSubmissionDiscussion;

-- Delete discussions generated as part of forumAdmin.feature
	 -- Create a new discussion 
DECLARE @testDiscussion AS uniqueidentifier;
SELECT @testDiscussion = id FROM [dbo].[Discussion] WHERE Title = 'autoTestDiscussion';
DELETE [dbo].[Comment] WHERE Discussion_Id = @testDiscussion;
DELETE [dbo].[Discussion] WHERE Id = @testDiscussion AND CreatedBy = @autoAdmin

-- Delete Folder generated as part of filesManagement.feature
DECLARE @adminGroup AS uniqueidentifier;
SELECT @adminGroup = Id FROM [dbo].[Group] WHERE Name = 'Automation Admin Group'
DELETE FROM [dbo].[Folder] WHERE Group_Id = @adminGroup AND Description = 'automation folder description' OR Title = 'eRacM5cnCLj1QiZ3fLxJzfyduloK9ICFtqTlNPJirR6Q8Sx66hslAURYY2BHhXUgI8W7liWxkEnSatHEowhmuSz15vXRFUyDzsk5pBUD0DHefy0yQkxX24t9jigs6gJzjCXh4uACDxhmXX1i8Zep34rBOv8WMA1Aom2QLQ6GTMtIaUX8uDSENmiEATt1JEk8aZaBJltyk3vBxCBSNBQY7eTgk5MuKdsU8Vc9VFyRI7LDoy9SKCrZQySCWhxn1bSCwlci2YACAf7tiscsxzXUN5u42lD5MUp5vePtpyPivLZivAvCkTAwjxpF4aidt9eo0ksBspZ0dLABHKIEmyfKvFUHxCCt2KmZgtuPMci8hnFIrgKensCH7fOpLa7ycZHDN6bwNsCtKZenECl9ydsv5tbVvQQKV97fSVg8aH9Rf3qaJYWZDv661JlY0SSwdG6V0DW4zdC3jgeIIMHVhQIoHQwAwWx7sh91vHMeUv4RyuHXN8sIYH1HmsYY9wGkHyr3HzjdaxIAxfLMrTlBokqMnzcq3i6tbBGcSetopjVAFr3btacpBIiRpH1cZKAnegU9wvt4EAPXlxZZ5MgQB5hAlcj9P50ZQTV8HTz5DjJ3Eh0sEFY5tHoaQRxEBFQIDXkDlOyFRrb4h8HjzKph3Im6OuMvwQTZjvD7D5B0buXpXv6UohrWxE2JVFa4YkAH8Kz9Geg1l9QT1dhI0zGLUUAGEBiz0j8NbDBgIqSORCXR3D35ohaor2WaWFouqn2eTNlphC3XEe9uxq3LCrtJ7kTM53Sg3SPAKaoeZh48cHyIxhnuupCWJtfGQTGyHVIkEqrGievotncg8NjnSeTDY8dL5O905loEAgXUKSCCfJAyH2JTAvnMcSOu0XKIgrDhlVgc3H1TKuAVcXdcsoDumHCSCFQlJP0DyQHyYyOzMkrbKW8viOFauAghwRFUBo9yvkZ3mpFapEmLnXpUdJMXQvXxR0mmnFYxQ5mYe1YHr4PZ' 
DELETE FROM [dbo].[Folder] WHERE Group_Id = @adminGroup AND IsDeleted = 1

-- Delete files uploaded as part of filesNavigation.feature
DECLARE @rootFolder AS uniqueidentifier;
SELECT @rootFolder = Id FROM [dbo].[Folder] WHERE title = 'Empty Folder' AND IsDeleted = 0

DELETE [dbo].[File] WHERE [ParentFolder] = @rootFolder

-- Reset Users to Pending Group Access groupAdmin.feature
	-- Approve group member request
	-- Reject group member request
UPDATE [dbo].[GroupUser] SET Approved = 0, ApprovedToJoinDateUTC = NULL, ApprovingMembershipUser_Id = NULL WHERE MembershipUser_Id = @autoUser2 AND Group_Id = @adminGroup;
UPDATE [dbo].[GroupUser] SET Rejected = 0, ApprovedToJoinDateUTC = NULL, ApprovingMembershipUser_Id = NULL WHERE MembershipUser_Id = @autoUser3 AND Group_Id = @adminGroup;

-- Remove users from groups added as part of automation
	-- Add registered user
DECLARE @publicGroup AS uniqueidentifier;
SELECT @publicGroup = Id FROM [dbo].[Group] WHERE Name = 'Automation Public Group'
DELETE FROM [dbo].[GroupUser] WHERE MembershipUser_Id = @autoUser2 AND Group_Id = @publicGroup

	-- Join a private group
DECLARE @privateGroup AS uniqueidentifier;
SELECT @privateGroup = Id FROM [dbo].[Group] WHERE Name = 'Automation Private Group'
DELETE FROM [dbo].[GroupUser] WHERE MembershipUser_Id = @autoUser AND Group_Id = @privateGroup

-- Remove deleted System Page from database generated by siteAdmin.feature
DELETE [dbo].[SystemPage] WHERE Slug = 'automation-content-page'
DELETE [dbo].[SystemPage] WHERE Slug = 'editable-system-page'
DELETE [dbo].[SystemPage] WHERE Slug = 'deletable-system-page'

--Delete new user details generated
	-- Invite User Form
DELETE [dbo].[GroupInvite] WHERE EmailAddress = 'autoTest@email.com'
	-- New user registration
DELETE [dbo].[MembershipUser] WHERE UserName = 'autoTest@email.com'

--Delete new group generated
	-- Group creation new fields	
DECLARE @groupid AS uniqueidentifier;
SELECT @groupid = id FROM [dbo].[Group] WHERE [Name] = 'alphaGroupTest';

DELETE [dbo].[GroupUser] WHERE Group_Id = @groupid
DELETE [dbo].[Group] WHERE Id = @groupid

-- Reset changes made to Automation Editable Group information
DECLARE @editgroup AS uniqueidentifier;
SELECT @editgroup = id FROM [dbo].[Group] WHERE [Name] = 'Automation Edited Group';
UPDATE [dbo].[Group] SET Name = 'Automation Editable Group',
						 Description = 'DO NOT USE - This group is reserved solely for use by our automated test scripts', 
		 				 PublicGroup = 0, 
		 				 Introduction = 'Introduction ',
						 Image = NULL,
		 				 AboutUs = NULL
					WHERE Id = @editgroup

-- Reset changes made to autoEditUser in edit profile tests
DECLARE @editUser AS uniqueidentifier;
SELECT @editUser = id FROM [dbo].[MembershipUser] WHERE Email = 'autoEditUser@test.co.uk'
UPDATE [dbo].[MembershipUser] SET FirstName = 'autoEdit', 
								  Surname = 'User',
								  Initials = 'AU',
								  Pronouns = ''
							  WHERE Id = @editUser

-- Reset changes made to docTest file in Automation Test Folder
DECLARE @docTest AS uniqueidentifier
SELECT @docTest = id FROM [dbo].[File] WHERE Title = 'Doc Test'
UPDATE [dbo].[File] SET Title = 'docTest', Description = 'test doc' WHERE Id = @docTest

-- Reset changes made to DeleteFolder 
DECLARE @deletefolder AS uniqueidentifier
SELECT @deletefolder = id FROM [dbo].[Folder] WHERE Title = 'DeleteFolder'
UPDATE [dbo].[Folder] SET IsDeleted = 0 WHERE Id = @deletefolder

-- Reset changes made to EditableFolder 
DECLARE @editfolder AS uniqueidentifier
SELECT @editfolder = id FROM [dbo].[Folder] WHERE Title = 'EditedFolder'
UPDATE [dbo].[Folder] SET Title = 'EditableFolder' WHERE Id = @editfolder