trigger:
  branches:
    include:
    - SPRINT

  paths:
    include:
    - futurenhs.automation/*

jobs:
- job:
  pool:
    vmImage: windows-latest

  steps:
    - task: NodeTool@0
      displayName: 'Use Node 14.15.0'
      inputs:
        versionSpec: 14.15.0
    - task: ExecuteSqlScript@1
      inputs:
        runOnAgent: true
        serverName: '$(devTestdbServerName)'
        databaseName: '$(devTestdbName)'
        useSQLAuthentication: true
        userName: 'devTestEnv1'
        password: 'devTestEnv2'
        scriptName: '/sqlQueries/fullAutomationDataSeed.sql'
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: custom
        verbose: false
        customCommand: 'i'
        workingDir: '$(Build.SourcesDirectory)/futurenhs.automation'
        
    - script: 'npm test $(TESTSUITE)'
      workingDirectory: '$(Build.SourcesDirectory)/futurenhs.automation'
      displayName: 'Execute Tests'
      continueOnError: true
    - task: ExecuteSqlScript@1
      inputs:
        runOnAgent: true
        serverName: '$(devTestdbServerName)'
        databaseName: '$(devTestdbName)'
        useSQLAuthentication: true
        userName: 'devTestEnv1'
        password: 'devTestEnv2'
        scriptName: '/sqlQueries/fullAutomationDataTeardown.sql'
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/wdio-*.log'
      inputs:
        testResultsFiles: '**/wdio-*.log'
        mergeTestResults: true