trigger: none
resources:
  pipelines:
  - pipeline: Dacpac-Pipeline-Execution
    source: dev.nhsimprovement.futurenhsopen-dacpac
    trigger:
      branches:
        include:
        - SPRINT

jobs:
- job:
  pool:
    vmImage: windows-latest

  steps:
    - task: NodeTool@0
      displayName: 'Use Node 14.16.1'
      inputs:
        versionSpec: 14.16.1

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: custom
        verbose: false
        customCommand: 'i'
        workingDir: '$(Build.SourcesDirectory)/futurenhs.automation'

    - script: '"./node_modules/.bin/wdio" wdio.headless.conf.js --baseUrl=$(ENVURL) --suite=fullRegression'
      workingDirectory: '$(Build.SourcesDirectory)/futurenhs.automation'
      displayName: 'Execute Tests'
      continueOnError: true
    
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/wdio-*.log'
      inputs:
        testResultsFiles: '**/wdio-*.log'
        mergeTestResults: true
        testRunTitle: Automated Front-End Regression
    - task: DeleteFiles@1
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/futurenhs.automation/junitResults'
        Contents: '**/wdio-*.log'
    
    - script: 'npm run scenario wdio.headless.conf.js Url=$(ENVURL) FNHS:FED02'
      workingDirectory: '$(Build.SourcesDirectory)/futurenhs.automation'
      displayName: 'Execute Tests'
      continueOnError: true
      failOnStderr: true
    - task: PublishTestResults@2
      displayName: 'Publish Accessibility Test Results'
      inputs:
        testResultsFiles: '**/wdio-*.log'
        mergeTestResults: true
        testRunTitle: Accessibility
      
    - task: PublishHtmlReport@1
      inputs:
        reportDir: '$(Build.SourcesDirectory)/futurenhs.automation/axeResults'
