jobs:
- job:
  pool:
    name: Azure Pipelines
    vmImage: windows-latest
    demands: npm

    variables:
    - name: TESTSUITE
      value: pipeline

  steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: custom
        verbose: false
        customCommand: 'i -force'
        workingDir: '$(Build.SourcesDirectory)/futurenhs.automation'
        
    - script: 'npm test $(TESTSUITE)'
      workingDirectory: '$(Build.SourcesDirectory)/futurenhs.automation'
      displayName: 'Execute Tests'
    - task: PublishTestResults@2
      displayName: 'Publish Test Results **/wdio-*.log'
      inputs:
        testResultsFiles: '**/wdio-*.log'