trigger: none
resources:
  pipelines:
  - pipeline: Dacpac-Pipeline-Execution
    source: dev.nhsimprovement.futurenhsopen-dacpac
    trigger:
      branches:
        include:
        - SPRINT

jobs:
- job:
  pool:
    vmImage: windows-latest

  steps:
  - task: CopyFiles@2
    displayName: 'Copy files for artifact'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/$(working-dir)/futurenhs.automation'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'FNHSAutomation'
      publishLocation: 'pipeline'