CREATE TABLE [dbo].[GroupSite]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [GroupId] UNIQUEIDENTIFIER NOT NULL, 
    [RootGuid] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_dbo.GroupId_dbo.Group_Id] FOREIGN KEY ([GroupId]) REFERENCES [Group]([Id])
)
